### PR TITLE
Add stripPathBefore option

### PR DESCRIPTION
**Pull request by mlarcher**
This option allows the user to remove everything up to a certain point in the path when the module/file name are created. It comes in handy when you need more control over the paths.

### CODE REVIEW

**Comment by mlarcher** [comment]
It fixes the use case initially described in https://github.com/javoire/browserify-ng-html2js/issues/13 and may help on https://github.com/javoire/browserify-ng-html2js/issues/22

**Comment by javoire** [comment]
Great

**Comment by javoire** [comment]
would you mind adding this to the readme? https://github.com/javoire/browserify-ng-html2js#b-with-gulp

**Comment by mlarcher** [comment]
As you have already merged the PR, I created a new one with the addition in README.md.

**Comment by javoire** [comment]
Great. Yeah I was a bit quick ;)

**Pull request merged**
